fix time zone consistency - was inconsistent outside of time zone local with client

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,6 +2,7 @@
 FC=`curl -X GET "https://api.weather.gov/points/$1,$2" -H "accept:application/geo+json" 2>/dev/null | grep hourly | awk 'match($0, /https:[^\"]+/){print substr($0, RSTART+23, RLENGTH-23)}'`
 RA=`curl -X GET "https://api.weather.gov/points/$1,$2" -H "accept:application/geo+json" 2>/dev/null | grep radar | awk 'match($0, /: \"..../){print substr($0, RSTART+4, 3)}'`
 ZONE=`curl -X GET "https://api.weather.gov/points/$1,$2" -H "accept:application/geo+json" 2>/dev/null | grep county | awk 'match($0, /county\/....../){print substr($0, RSTART+7, 6)}'`
+TIMEZONE=`curl -X GET "https://api.weather.gov/points/$1,$2" -H "accept:application/geo+json" 2>/dev/null | grep time | awk 'match($0, /timeZone\": \"[^\"]+/){print substr($0, RSTART+12, RLENGTH-12)}'`
 if [ "$FC" == "" ]; then
     echo "Could not determine forecast information URL"
     exit 1
@@ -14,6 +15,10 @@ if [ "$ZONE" == "" ]; then
     echo "Could not determine alert zone"
     exit 1
 fi
+if [ "$TIMEZONE" == "" ]; then
+    echo "Could not determine time zone"
+    exit 1
+fi
 if [ "$3" == "" ]; then
     LO="Local"
 else
@@ -23,7 +28,8 @@ echo "var config = {" > config.js
 echo "     forecastURL  : \"api.weather.gov\"," >> config.js
 echo "     forecastPath : \"$FC\"," >> config.js
 echo "     radarStation : \"$RA\"," >> config.js
-echo "     zone         : \"$ZONE\"" >> config.js
+echo "     zone         : \"$ZONE\"," >> config.js
+echo "     timeZone     : \"$TIMEZONE\"" >> config.js
 echo "};" >> config.js
 echo "module.exports=config;" >> config.js
 sed s/XXX/$RA/ indexTemplate.html > index.html
